version: '3.8'
services:
  operation-manager:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      - SERVER_PORT=8081
      - DB_HOST=database
      - DB_PORT=5435
      - DB_NAME=accounts_db
      - DB_USER=postgres
      - DB_PASS=1234
  database:
    image: postgres:10.7
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=accounts_db
    volumes:
      - psql_data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  psql_data: