server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5435/accounts_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO