server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  application:
    name: accounts
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:accounts_db}"
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        loggerLevel: full
      exchangerates:
        connectTimeout: 5000
        readTimeout: 5000

variables:
  exchange-rate-api-key: e4e3a91ef3fe769c1684a75eeaf924e5

logging:
  level:
    root: DEBUG