-- liquibase formatted sql

-- changeset erivnracz:1646514184448-1
CREATE TABLE account
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    iban     VARCHAR(255)                            NOT NULL,
    currency VARCHAR(255)                            NOT NULL,
    balance  DECIMAL                                 NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

-- changeset erivnracz:1646514184448-2
ALTER TABLE account
    ADD CONSTRAINT uc_account_iban UNIQUE (iban);

